import type { VideoCardData } from '@/components/video-card';

const thumb = (color: string) =>
  `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 270 480"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="%23${color}"/><stop offset="1" stop-color="%23111"/></linearGradient></defs><rect fill="url(%23g)" width="270" height="480"/></svg>`;

export const mockHotVideos: VideoCardData[] = [
  {
    id: 'v1',
    rank: 1,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('5b3a82'),
    title: '결말 1초컷 — 8월 영드짜 레전드 모음',
    channelName: '건봉이티비',
    folder: '영드짜',
    totalViews: 3_120_000,
    recentGrowthPerHour: 33_000,
    peakGrowthPerHour: 41_000,
    channelAvgMultiplier: 12.4,
    starred: true,
  },
  {
    id: 'v2',
    rank: 2,
    platform: 'TIKTOK',
    thumbnailUrl: thumb('6b3a3a'),
    title: '딱 5초만 보세요',
    channelName: 'ydb_compile',
    folder: '영드짜',
    totalViews: 2_100_000,
    recentGrowthPerHour: 24_500,
    channelAvgMultiplier: 8.8,
  },
  {
    id: 'v3',
    rank: 3,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('3a5b6b'),
    title: '동물 빡친 순간 모음 ZIP',
    channelName: 'animal_zip',
    folder: '해짜 (동물)',
    totalViews: 1_800_000,
    recentGrowthPerHour: 18_200,
    channelAvgMultiplier: 9.4,
  },
  {
    id: 'v4',
    rank: 4,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('5b6b3a'),
    title: '한국이 또 1등 했다는 분야',
    channelName: '국뽕TV',
    folder: '국뽕',
    totalViews: 1_400_000,
    recentGrowthPerHour: 8_400,
    channelAvgMultiplier: 3.8,
  },
  {
    id: 'v5',
    rank: 5,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('4a3a6b'),
    title: '나혼자산다 명장면 ZIP',
    channelName: 'movie_kr',
    folder: '예능짜집기',
    totalViews: 980_000,
    recentGrowthPerHour: 6_100,
    channelAvgMultiplier: 4.6,
  },
  {
    id: 'v6',
    rank: 6,
    platform: 'TIKTOK',
    thumbnailUrl: thumb('6b5b3a'),
    title: '오늘자 밈 짜집기',
    channelName: 'meme_kr',
    folder: '인스타 틱톡 짜집기',
    totalViews: 880_000,
    recentGrowthPerHour: 5_900,
    channelAvgMultiplier: 3.1,
  },
  {
    id: 'v7',
    rank: 7,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('3a6b4a'),
    title: '롤 미친 클러치 모음',
    channelName: 'lol_clutch',
    folder: '게임 | 롤',
    totalViews: 760_000,
    recentGrowthPerHour: 5_200,
    channelAvgMultiplier: 4.2,
  },
  {
    id: 'v8',
    rank: 8,
    platform: 'INSTAGRAM',
    thumbnailUrl: thumb('6b3a5b'),
    title: '아기 첫 걸음 모먼트',
    channelName: 'baby_steps',
    folder: '아기',
    totalViews: 610_000,
    recentGrowthPerHour: 4_400,
    channelAvgMultiplier: 2.8,
  },
  {
    id: 'v9',
    rank: 9,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('3a4a5b'),
    title: '블랙박스 깜놀 순간',
    channelName: 'blackbox_kr',
    folder: '블랙박스',
    totalViews: 540_000,
    recentGrowthPerHour: 3_900,
    channelAvgMultiplier: 3.4,
  },
  {
    id: 'v10',
    rank: 10,
    platform: 'TIKTOK',
    thumbnailUrl: thumb('5b3a3a'),
    title: '잡학 1분 — 알고리즘이 좋아함',
    channelName: 'trivia_1min',
    folder: '잡학상식',
    totalViews: 480_000,
    recentGrowthPerHour: 3_200,
    channelAvgMultiplier: 2.9,
  },
  {
    id: 'v11',
    rank: 11,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('3a5b3a'),
    title: '해외 반응 — 한식 처음 본 외국인',
    channelName: 'foreign_react',
    folder: '해외 영드짜',
    totalViews: 420_000,
    recentGrowthPerHour: 2_800,
    channelAvgMultiplier: 3.0,
  },
  {
    id: 'v12',
    rank: 12,
    platform: 'INSTAGRAM',
    thumbnailUrl: thumb('4a5b6b'),
    title: '주말 요리 — 30분 한그릇',
    channelName: 'cook_30',
    folder: '요리',
    totalViews: 380_000,
    recentGrowthPerHour: 2_400,
    channelAvgMultiplier: 2.5,
  },
  {
    id: 'v13',
    rank: 13,
    platform: 'YOUTUBE',
    thumbnailUrl: thumb('6b4a3a'),
    title: '대기업 신입 첫날.zip',
    channelName: 'corp_zip',
    folder: '대기업',
    totalViews: 340_000,
    recentGrowthPerHour: 2_100,
    channelAvgMultiplier: 3.6,
  },
  {
    id: 'v14',
    rank: 14,
    platform: 'TIKTOK',
    thumbnailUrl: thumb('3a3a6b'),
    title: '아이돌 무대 직캠 모음',
    channelName: 'idol_fancam',
    folder: '아이돌 팬튜브',
    totalViews: 320_000,
    recentGrowthPerHour: 1_900,
    channelAvgMultiplier: 2.3,
  },
];

const hashtagThumb = (color: string) =>
  `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 270 480"><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="%23${color}"/><stop offset="1" stop-color="%23222"/></linearGradient></defs><rect fill="url(%23g)" width="270" height="480"/></svg>`;

/**
 * 해시태그 기반 발견(unknown channels). channelAvgMultiplier는 채널 평균을
 * 모르므로 비워두고, 대신 좋아요/조회 비율과 절대 24h 조회량 위주로 표시.
 */
export const mockHashtagFeed: (VideoCardData & { hashtag: string })[] = [
  {
    id: 'h1',
    rank: 1,
    platform: 'TIKTOK',
    thumbnailUrl: hashtagThumb('7a3a82'),
    title: '국뽕 1분 컷 — 외국인 진심 반응',
    channelName: 'unknown_42k',
    folder: '국뽕',
    hashtag: '#국뽕',
    totalViews: 4_200_000,
    recentGrowthPerHour: 92_000,
    peakGrowthPerHour: 110_000,
  },
  {
    id: 'h2',
    rank: 2,
    platform: 'INSTAGRAM',
    thumbnailUrl: hashtagThumb('3a7a82'),
    title: '강아지 첫 외출 모먼트',
    channelName: 'pups_kr',
    folder: '해짜 (동물)',
    hashtag: '#강아지',
    totalViews: 2_800_000,
    recentGrowthPerHour: 48_000,
  },
  {
    id: 'h3',
    rank: 3,
    platform: 'TIKTOK',
    thumbnailUrl: hashtagThumb('826b3a'),
    title: '영드짜 레전드 ZIP',
    channelName: 'kdrama_zipclip',
    folder: '영드짜',
    hashtag: '#영드짜',
    totalViews: 1_900_000,
    recentGrowthPerHour: 31_000,
  },
  {
    id: 'h4',
    rank: 4,
    platform: 'INSTAGRAM',
    thumbnailUrl: hashtagThumb('3a826b'),
    title: '오늘자 짤 모음',
    channelName: 'meme_daily_kr',
    folder: '예능짜집기',
    hashtag: '#예능',
    totalViews: 1_400_000,
    recentGrowthPerHour: 22_000,
  },
  {
    id: 'h5',
    rank: 5,
    platform: 'TIKTOK',
    thumbnailUrl: hashtagThumb('6b3a82'),
    title: '아기 잠투정 진정 영상',
    channelName: 'baby_calm',
    folder: '아기',
    hashtag: '#육아',
    totalViews: 1_100_000,
    recentGrowthPerHour: 18_400,
  },
  {
    id: 'h6',
    rank: 6,
    platform: 'TIKTOK',
    thumbnailUrl: hashtagThumb('826b6b'),
    title: '롤 클러치 — 0.1초 차이',
    channelName: 'lol_moment',
    folder: '게임 | 롤',
    hashtag: '#롤',
    totalViews: 980_000,
    recentGrowthPerHour: 14_200,
  },
  {
    id: 'h7',
    rank: 7,
    platform: 'INSTAGRAM',
    thumbnailUrl: hashtagThumb('3a3a82'),
    title: '백종원 신작 레시피 따라함',
    channelName: 'cook_kr',
    folder: '요리',
    hashtag: '#요리',
    totalViews: 720_000,
    recentGrowthPerHour: 9_800,
  },
  {
    id: 'h8',
    rank: 8,
    platform: 'TIKTOK',
    thumbnailUrl: hashtagThumb('826b82'),
    title: '아이돌 무대 직캠 — 4K 풀버전',
    channelName: 'fancam_4k',
    folder: '아이돌 팬튜브',
    hashtag: '#아이돌',
    totalViews: 540_000,
    recentGrowthPerHour: 7_200,
  },
];
